default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: myapp_development
  username: christian
test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: d9ski16fii8soo
  host: ec2-54-221-253-117.compute-1.amazonaws.com
  username: icgrxvkbfqmdeh
  port: 5432
  password: Q9bdK9Nn3Bh4Q4CL44pWXYE8qv

